image: docker:latest

variables:
  IMAGE_NAME: "${REGISTRY_NAME}/chtw-action-ci:${CI_COMMIT_REF_NAME}"
  BIN_NAME: "action-ci"

cache:
  paths:
    - .m2/

stages:
  - package
  - build

package:
  image: maven:3.6-jdk-8-alpine
  tags:
    - public-runner001
  stage: package
  script:
    - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
            <localRepository>/cache/.m2</localRepository>
            <mirrors>
              <mirror>
                <id>nexus-aliyun</id>
                <mirrorOf>*</mirrorOf>
                <name>Nexus aliyun</name>
                <url>http://maven.aliyun.com/nexus/content/groups/public</url>
              </mirror>
            </mirrors>
            </settings>' > $HOME/.m2/settings.xml
    - mvn clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar    # 将maven构建成功的jar包作为构建产出导出，可在下一个stage的任务中使用


build:
  stage: build
  tags:
    - public-runner001
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
    - tags
  dependencies:
    - package
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${REGISTR_NAME}
    - docker build . -t ${IMAGE_NAME}
    - docker push ${IMAGE_NAME}
