name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/chtw/action-ci/chtw/action-ci:master
    
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ispeakcode/docker-githubaction
        image_name: registry.cn-hangzhou.aliyuncs.com/chtw/action-ci/chtw/action-ci:master
        repository: registry.cn-hangzhou.aliyuncs.com/chtw/action-ci/chtw/action-ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
