name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_NAME }}/chtw/action-ci::$(date +%s)
    
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ispeakcode/docker-githubaction
        image_name: ${{ secrets.REGISTRY_NAME }}/chtw/action-ci::$(date +%s)
        repository: ${{ secrets.REGISTRY_NAME }}/chtw/action-ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
